### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by joker63** [cheshir/go-mq#18]
If I add information about the queue priority to the config file
`"options": {
          "durable": true,
          "args": {
            "x-max-priority": 9
          }
        }`

In the console I get error
panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}

How will write priority in config file?

**Comment by cheshir** [comment]
Thanks for the issue. I'll check it soon.

**Comment by cheshir** [comment]
@joker63 hm, can you make a snippet with example please? I can't reproduce this bug.
Check [this gist](https://gist.github.com/cheshir/653b3c60903fcf42e60c0f6c14a9801e) please.

**Comment by cheshir** [comment]
I can't reproduce your bug. But I've found another one. 
If you properly filled args you will get error: `table field "x-max-priority" value %!t(int=9) not supported`.
I've fixed this issue in [this PR](https://github.com/cheshir/go-mq/pull/19).
[Here is the snippet](https://gist.github.com/cheshir/653b3c60903fcf42e60c0f6c14a9801e) with ready-to-use example. Please update package and try code from gist. 

I'm waiting for your feedback.

**Comment by joker63** [comment]
yaml config is works fine. Json not work :(
`package main

import (
	"encoding/json"
	"fmt"

	"github.com/cheshir/go-mq"
)

var externalConfiguration = []byte(`
	{
		"dsn": "amqp://seldonUser:seldonUser@virt46",
		"exchanges": [
			{
				"name": "rt_dev_report",
				"type": "direct",
				"options": {
					"durable": true
				}
			}
		],
		"queues": [
			{
				"name": "rt_dev_report_buisnessIndicator",
				"exchange": "rt_dev_report",
				"routing_key": "route",
				"options": {
					"args": {
						"x-max-priority": 9
					},
					"durable": true
				}
			}
		]
	}
`)

func main() {
	var config mq.Config
	//yaml.Unmarshal(externalConfiguration, &config)
	err := json.Unmarshal(externalConfiguration, &config)
	if err != nil {
		panic(err)
	}
	fmt.Println(config)
	rabbit, err := mq.New(config)
	if err != nil {
		panic("Error during mq initialization: " + err.Error())
	}

	go func() {
		if err := <-rabbit.Error(); err != nil {
			panic("Caught rmq error: " + err.Error())
		}
	}()

	println("Message have sent. Check it in queue.")

	rabbit.Close()
}
`

**Comment by cheshir** [comment]
LOL. YAML 1.2 a superset of JSON. So you can unmarshal json config with `gopkg.in/yaml.v2` without any problem.
I also got an error with `encoding/json`. Right now you can use `gopkg.in/yaml.v2` to solve this problem. I'm gonna check what the problem with `encoding/json`. Stay tuned.

**Comment by cheshir** [comment]
@joker63 The problem occurs because by default `gopkg.in/yaml.v2` decodes collections to `map[interface{}]interface{}` and `encoding/json` decodes them to `map[string]interface{}`. I will think how properly fix this problem. 
As a quick solution you can use `gopkg.in/yaml.v2` to unmarshal config as I suggest before.

**Comment by cheshir** [comment]
I've fixed the problem in #20. @joker63 please check it. Does it work for you?
