### ISSUE TITLE
Enable Mocking/Testing  by exporting brokerIsMocked var ?

### ISSUE THREAD

**Issue by snemitz** [cheshir/go-mq#27]
Current Problem: I'd like to use the go-mq library within a service to connect to a MQ - to test that the service works fine, I want to use the a fake server. 

As I was going through the code, it seems that the variable "brokerIsMocked" must be set to true, to allow connection to faked server. From another package I can't do this - obviously.

Am I missing something? Is there a another way to connect to a fake server? Like a flag with the mq.Config?

Kind regards !

PS: Nice work with the lib - really like it.

**Comment by cheshir** [comment]
Hi. Thanks for your feedback.
It seems that the simplest solution for you is to mock library (MQ interface).
The underline library wabbit is a quite buggy when used in testing and works bad in concurrent environment. It's possible to tweak it, but this way is more complex then mocked interface.

If mocking is not your way I can provide ability to turn on test mode using config option or exposed method.

**Comment by snemitz** [comment]
I think it would be great to have both options: Mocking and using a test faked server.
Setting via config is imho the best way. But exposing a method to set the variable would also be fine for me.

**Comment by cheshir** [comment]
@snemitz check it please: https://github.com/cheshir/go-mq/pull/28

**Comment by snemitz** [comment]
Looks fine to me. Thank you very much

**Comment by cheshir** [comment]
@snemitz please pay attention that PR has been merged to 1.0.0 version that contains some breaking changes in API.
