### ISSUE TITLE
Read all messages in a queue

### ISSUE THREAD

**Issue by cd-rum** [cheshir/go-mq#30]
Is there an established method to grab all the messages in a certain queue? I don't want to reinvent the wheel, and I wasn't sure where else to ask. Thanks

**Comment by cheshir** [comment]
Hey @cd-rum.

To get messages from the queue you need to setup consumer. More details about routing messages to the specific consumer you can find in the official RabbitMQ documentation.

I prepared for you a simple example of how to consume messages using go-mq library: https://gist.github.com/cheshir/58112ee73d126c91c583aecef2f25242

Feel free to ask any questions related to rabbitmq.

**Comment by cd-rum** [comment]
Thanks so much!

**Comment by cheshir** [comment]
@cd-rum you’re welcome! 🙂
