### ISSUE TITLE
Cluster connection

### ISSUE THREAD

**Issue by doranych** [cheshir/go-mq#33]
### Suggestion
Create cluster connection
For backward compatibility it's possible to use list of cluster nodes in single string separated by comma
```yaml
dsn:  amqp://login:password@host1:port/virtual_host,amqp://login:password@host2:port/virtual_host,amqp://login:password@host3:port/virtual_host
```
Same scheme is typically used to describe kafka cluster connection

### Discuss 
You always have rabbit cluster even if there's only one node in it. Right? 
I think it's possible to iterate over cluster nodes before re-connection to the same node

**Comment by doranych** [comment]
or it's always possible to add additional method for exactly cluster connection

**Comment by cheshir** [comment]
@doranych thank you for the great proposal.

Right now I don't have enough time to add support for clustering so PR is highly welcome.

Btw, if you want to use this library with rabbit cluster right now consider using DNS balancing (something like kubernetes services).

**Comment by doranych** [comment]
@cheshir i did PR. Just kind remind to view that at some point
